translation_replace:
  ple: 
files:
  - source: /testtwo/*.xml
    translation: /ttwo/%two_letters_code%.%file_extension
  - source: Exam_ple.xml
    translation: /qqq/%two_letters_code%.%file_extension%
    languages_mapping:
      two_letters_code:
        ru: ros
        uk: ukr
  - source: /2019-08-26-OB-0-9-2b.md
    translation: /%two_letters_code%/%file_name%.%file_extension%
