files:
  - source: /Sample.csv
    translation: /spreadsheets/%locale%.%file_extension%
    first_line_contains_header: 1
    scheme: 'identifier,context,source_or_translation'
  - source: /Multilingual_spreadsheet_sample.csv
    translation: /spreadsheets/%locale%/%original_file_name%
    multilingual_spreadsheet: 1
    first_line_contains_header: 1
    scheme: 'identifier,context,source_phrase,es-ES,fr,max_length,ru,it'
  - source: /Example.xml
    translation: /%language%/%original_file_name%
    content_segmentation: 0
    translatable_elements:
      - /data/string
  - source: /test.xml
    translation: /xmltest/%locale%.%file_extension%
    translatable_elements:
      - bookstore/book/title
