files:
  - source: /testtwo/*.xml
    translation: /ttwo/%two_letters_code%.%file_extension
  - source: Example.xliff
    translation: /tesste/%two_letters_code%.%file_extension%
translation_replace: {
"ple" : ""
}
