translation_replace:
  ple: 
files:
  - source: /testtwo/*.xml
    translation: /ttwo/%two_letters_code%.%file_extension
  - source: Exam_ple.xml
    translation: /qqq/%two_letters_code%.%file_extension%
  

