files:
  - source: /sorryn.xml
    translation: /update/%two_letters_code%.%file_extension%
    update_option: update_as_unapproved
    translate_attributes: 0
    content_segmentation: 0
  - source: /testtwo/*.xml
    ignore:
      - /testtwo/sorryq.xml
    translation: /ttwo/%two_letters_code%.%file_extension%
