files:
  - source: /test.properties
    translation: /trans/%two_letters_code%/%original_file_name%
    escape_special_characters: 0
  - source: newtest.xml
    translation: /test22/%two_letters_code%.%file_extension%
  - source: /thisis.html
    translation: /transl/%two_letters_code%.%file_extension%
  - source: /Example - Copy.json
    translation: /test/%locale%.%file_extension%
