files:
  - source: /sorryn.xml
    translation: /update/%two_letters_code%.%file_extension%
    translate_attributes: 0
    content_segmentation: 0
    update_option: update_as_unapproved
  - source: /testtwo/*.xml
    ignore:
      - /testtwo/sorryq.xml
    translation: /ttwo/%two_letters_code%.%file_extension%
  - source: /index.twig
    translation: /destest/%locale%.twig
    dest : "/pp/inde.html",
    type" : "html"
