"files" : [
  {
    "source" : "/CommentReplyMessages_en.properties",
    "translation" : "/%file_name%_%two_letters_code%.%file_extension%",
    "translation_replace": {
        "_en" : ""
    }
  },
    
    {
    "source" : "/Sample.csv",
    "translation" : "/lol/%two_letters_code%.%file_extension%",
    "scheme" : "identifier,context,source_phrase,,translation"
    }
]
