translation_replace:
  ple: 
files:
  - source: /testtwo/*.xml
    translation: /ttwo/%two_letters_code%.%file_extension
  - source: Exam_ple.xml
    translation: /qqq/%two_letters_code%.%file_extension%
    - source: /core/src/main/resources/locales/en_US.yml
translation: /core/src/main/resources/locales/%locale_with_underscore%.yml
"source" : "/locale/en*.po",
"translation" : "/locale/%two_letters_code%%original_file_name%",
"languages_mapping" : {
"two_letters_code" : {
"ru" : "ros",
"uk" : "ukr"
    
        
