files:
  - source: /all_translatioens.xlsx
    translation: /Test/%two_letters_code%.%file_extension%
    first_line_contains_header: 1
    scheme: 'identifier,context,source_phrase,max_length,translation'
