files:
  - source: /newtest.xml
    translation: /%two_letters_code%/translation/%two_letters_code%.%file_extension%
  - source: /sorryn.xml
    translation: /Testik/%two_letters_code%.%file_extension%
